#!/bin/bash
#
# Create configuration links in home directory.
#

set -e

BASE_DIR="$( cd -P "$( dirname "$(readlink -f $0)" )" && pwd -L )"

ln -s -b -v -T $BASE_DIR/bin/ ~/bin

ln -s -b -v -T $BASE_DIR/zsh/alias ~/.alias

# TODO: remove or split
ln -s -b -v -T $BASE_DIR/zsh/profile ~/.profile

ln -s -b -v -T $BASE_DIR/vim ~/.vim
ln -s -b -v -T $BASE_DIR/vimrc ~/.vimrc

# TODO: Simplify path
ln -s -b -v -T $BASE_DIR/zsh/zsh ~/.zsh
ln -s -b -v -T $BASE_DIR/zsh/zshrc ~/.zshrc
ln -s -b -v -T $BASE_DIR/zsh/zshenv ~/.zshenv
ln -s -b -v -T $BASE_DIR/zsh/zshprofile ~/.zshprofile

ln -s -b -v -T $BASE_DIR/git/gitconfig ~/.gitconfig
ln -s -b -v -T $BASE_DIR/git/githelpers ~/.githelpers
ln -s -b -v -T $BASE_DIR/git/gitignore ~/.gitignore

ln -s -b -v -T $BASE_DIR/ctags/ctags ~/.ctags

ln -s -b -v -T $BASE_DIR/Xresources ~/.Xresources

ln -s -b -v -T $BASE_DIR/ssh/config ~/.ssh/config

ln -s -b -v -T $BASE_DIR/vimify/inputrc ~/.inputrc

ln -s -b -v -T $BASE_DIR/xinitrc ~/.xinitrc

[ ! -d ~/.irssi ] &&  mkdir ~/.irssi
cp -b $BASE_DIR/irssi/config ~/.irssi/config

[ ! -d ~/.config ] && mkdir ~/.config
for file in `ls $BASE_DIR/config`; do
    ln -s -b -v -T $BASE_DIR/config/$file ~/.config/$file
done

ln -s -b -v -T $BASE_DIR/Xmodmap ~/.Xmodmap
